export const GET_SHOP_REQUEST = 'GET_SHOP_REQUEST';
export const GET_SHOP_SUCCESS = 'GET_SHOP_SUCCESS';
export const GET_SHOP_FAILED = 'GET_SHOP_FAILED';
export const GET_LOCALE = 'GET_LOCALE';
export const SET_LOCALE = 'SET_LOCALE';
export const GET_ICON = 'GET_ICON';
export const SET_ICON = 'SET_ICON';
export const GET_FILTERS_REQUEST = 'GET_FILTERS_REQUEST';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';
export const GET_FILTERS_FAILED = 'GET_FILTERS_FAILED';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
export const GET_PRODUCT_ATTRIBUTES_REQUEST = 'GET_PRODUCT_ATTRIBUTES_REQUEST';
export const GET_PRODUCT_ATTRIBUTES_SUCCESS = 'GET_PRODUCT_ATTRIBUTES_SUCCESS';
export const GET_PRODUCT_ATTRIBUTES_FAILED = 'GET_PRODUCT_ATTRIBUTES_FAILED';
export const GET_SUPPLIER_REQUEST = 'GET_SUPPLIER_REQUEST';
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS';
export const GET_SUPPLIER_FAILED = 'GET_SUPPLIER_FAILED';
export const GET_PRODUCT_REVIEWS_REQUEST = 'GET_PRODUCT_REVIEWS_REQUEST';
export const GET_PRODUCT_REVIEWS_SUCCESS = 'GET_PRODUCT_REVIEWS_SUCCESS';
export const GET_PRODUCT_REVIEWS_FAILED = 'GET_PRODUCT_REVIEWS_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const SET_USER = 'SET_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_ORDER_LIST_REQUEST = 'GET_ORDER_LIST_REQUEST';
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';
export const GET_ORDER_LIST_FAILED = 'GET_ORDER_LIST_FAILED';
export const GET_SUGGESTED_ORDERS_REQUEST = 'GET_SUGGESTED_ORDERS_REQUEST';
export const GET_SUGGESTED_ORDERS_SUCCESS = 'GET_SUGGESTED_ORDERS_SUCCESS';
export const GET_SUGGESTED_ORDERS_FAILED = 'GET_SUGGESTED_ORDERS_FAILED';
export const GET_SUPPLIER_PRODUCTS_REQUEST = 'GET_SUPPLIER_PRODUCTS_REQUEST';
export const GET_SUPPLIER_PRODUCTS_SUCCESS = 'GET_SUPPLIER_PRODUCTS_SUCCESS';
export const GET_SUPPLIER_PRODUCTS_FAILED = 'GET_SUPPLIER_PRODUCTS_FAILED';
export const GET_VARIABLE_ATTRIBUTES_REQUEST = 'GET_VARIABLE_ATTRIBUTES_REQUEST';
export const GET_VARIABLE_ATTRIBUTES_SUCCESS = 'GET_VARIABLE_ATTRIBUTES_SUCCESS';
export const GET_VARIABLE_ATTRIBUTES_FAILED = 'GET_VARIABLE_ATTRIBUTES_FAILED';
export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAILED = 'GET_PRODUCT_DETAILS_FAILED';
export const GET_SUPPLIER_PRODUCT_REQUEST = 'GET_SUPPLIER_PRODUCT_REQUEST';
export const GET_SUPPLIER_PRODUCT_SUCCESS = 'GET_SUPPLIER_PRODUCT_SUCCESS';
export const GET_SUPPLIER_PRODUCT_FAILED = 'GET_SUPPLIER_PRODUCT_FAILED';
export const GET_PRODUCT_DETAIL_REQUEST = 'GET_PRODUCT_DETAIL_REQUEST';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILED = 'GET_PRODUCT_DETAIL_FAILED';
export const GET_SALES_REQUEST = 'GET_SALES_REQUEST';
export const GET_SALES_SUCCESS = 'GET_SALES_SUCCESS';
export const GET_SALES_FAILED = 'GET_SALES_FAILED';
export const GET_SALE_REQUEST = 'GET_SALE_REQUEST';
export const GET_SALE_SUCCESS = 'GET_SALE_SUCCESS';
export const GET_SALE_FAILED = 'GET_SALE_FAILED';
export const GET_MESSAGES_HISTORY_REQUEST = 'GET_MESSAGES_HISTORY_REQUEST';
export const GET_MESSAGES_HISTORY_SUCCESS = 'GET_MESSAGES_HISTORY_SUCCESS';
export const GET_MESSAGES_HISTORY_FAILED = 'GET_MESSAGES_HISTORY_FAILED';
export const CHAT_CONNECT = 'CHAT_CONNECT';
export const SET_CHAT_CONNECT = 'SET_CHAT_CONNECT';
export const GET_SUPPLIER_REVIEWS_REQUEST = 'GET_SUPPLIER_REVIEWS_REQUEST';
export const GET_SUPPLIER_REVIEWS_SUCCESS = 'GET_SUPPLIER_REVIEWS_SUCCESS';
export const GET_SUPPLIER_REVIEWS_FAILED = 'GET_SUPPLIER_REVIEWS_FAILED';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';
export const UPDATE_BASKET_REQUEST = 'UPDATE_BASKET_REQUEST';
export const UPDATE_BASKET_SUCCESS = 'UPDATE_BASKET_SUCCESS';
export const UPDATE_BASKET_FAILED = 'UPDATE_BASKET_FAILED';
export const GET_BASKET_REQUEST = 'GET_BASKET_REQUEST';
export const GET_BASKET_SUCCESS = 'GET_BASKET_SUCCESS';
export const GET_BASKET_FAILED = 'GET_BASKET_FAILED';
export const GET_DISPUTES_REQUEST = 'GET_DISPUTES_REQUEST';
export const GET_DISPUTES_SUCCESS = 'GET_DISPUTES_SUCCESS';
export const GET_DISPUTES_FAILED = 'GET_DISPUTES_FAILED';
export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_FAILED = 'GET_FAVORITES_FAILED';
export const GET_SUPPLIERS_REQUEST = 'GET_SUPPLIERS_REQUEST';
export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';
export const GET_SUPPLIERS_FAILED = 'GET_SUPPLIERS_FAILED';
export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED';

export const desc = 'desc';
export const asc = 'asc';

export const languages = [
    {name: 'russian', value: 'ru'},
    {name: 'english', value: 'en-US'},
    {name: 'korean', value: 'ko'}
];

export const currencies = [
    {name: 'russianRuble', value: 'rub'},
    {name: 'usDollar', value: 'usd'},
    {name: 'koreanWon', value: 'krw'}
];

export const ratingStars = Object.fromEntries(Array.of(0, 0, 0, 0, 0).entries());